export const PULL_MEAL_HISTORY = "PULL_MEAL_HISTORY";
export const REMOVE_FROM_HISTORY = "REMOVE_FROM_HISTORY";
export const EDIT_SAVED_MEAL = "EDIT_SAVED_MEAL";
export const REMOVE_SAVED_MEAL_FROM_EDIT = "REMOVE_SAVED_MEAL_FROM_EDIT";