export const ADD_TO_SUMMARY = "ADD_TO_SUMMARY";
export const REMOVE_FROM_SUMMARY = "REMOVE_FROM_SUMMARY";
export const INDUCT_SAVED_SUMMARY = "INDUCT_SAVED_SUMMARY";
export const RESET_SUMMARY = "RESET_SUMMARY";